
type Query {
  hello(user: User_input!): String!
  me: User!
  ping: String!
}

input User_input {
  name: String!
}

type Post {
  date: Int
  author: [User]
}

type User {
  name: String
  posts: [Post]
}

type Mutation {
  sendMessage(message: String!): String!
}

type Subscription {
  me: User!
  onMessage: String
}