type Query {
  hello(user: User_input!): String!
  me: User
  ping: String!
}

input User_input {
  name: String!
}

type User {
  name: String!
}

type Mutation {
  sendMessage(message: String!): String!
}

type Subscription {
  onMessage: String
}