type Query {
	hello(name: String!): String!
	hello_user(user: User!): String!
	me: User
}

type User {
	name: String!
}

type Mutation {
	sendMessage(message: String!): String!
}

type Subscription {
	onMessage: String
}